services:
  frontend:
    container_name: frontend-vite-cont
    extra_hosts:
      - host.docker.internal:host-gateway
    build:
      context: ./frontend-vite
      dockerfile: Dockerfile
    ports:
      - 5173:5173
  backend:
    container_name: backend-hardhat-cont
    # env_file:
    #   - path: ./backend-hardhat/.env
    #     required: true # default
    extra_hosts:
      - host.docker.internal:host-gateway
    build:
      context: ./backend-hardhat
      dockerfile: Dockerfile
    ports:
      - 8545:8545