services:
  frontend:
    container_name: frontend-vite-cont 
    extra_hosts:
      - host.docker.internal:host-gateway
    build:
      context: ./frontend-vite
      dockerfile: Dockerfile
    ports:
      - 5173:5173
  backend:
    container_name: backend-hardhat-cont
    extra_hosts:
      - host.docker.internal:host-gateway
    build:
      context: ./backend-hardhat
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8545:8545
