volumes:
  shared-volume:

services:
#building backend
  backend:
    container_name: backend-hardhat-cont
    env_file:
      - path: ./backend-hardhat/.env
        required: true # default
    extra_hosts:
      - host.docker.internal:host-gateway
    build:
      context: ./backend-hardhat
      dockerfile: Dockerfile
    ports:
      - 8545:8545
    volumes:
    - shared-volume:/app/artifacts/contracts/IPFSDriveContract_Main.sol

# building frontend
  frontend:
    container_name: frontend-vite-cont
    depends_on:
      - backend
    extra_hosts:
      - host.docker.internal:host-gateway
    build:
      context: ./frontend-vite
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
       - shared-volume:/app/src/context-state